name: Run Pest tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Pest tests
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Code ğŸ”
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer âš™ï¸
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Install dependencies ğŸ“¦
        run: composer install --prefer-dist --no-interaction --no-scripts

      - name: Run Laravel Pint ğŸ”§
        uses: aglipanci/laravel-pint-action@2.4
        with:
          configPath: pint.json

      - name: Commit Changes ğŸš€
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Laravel Pint
