name: Run Pest tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: library_tests
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code ğŸ”
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer âš™ï¸
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pdo_mysql

      - name: Cache composer dependencies ğŸ“¦
        uses: actions/cache@v4
        with:
          path: vendor/
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-cache-

      - name: Install dependencies ğŸª›
        run: composer install --no-progress --no-suggest --optimize-autoloader --no-interaction --prefer-dist --no-scripts

      - name: Create environment file ğŸª›
        run: mv .env.testing .env

      - name: Run Pest ğŸš€
        run: ./vendor/bin/pest --configuration=phpunit.xml --colors=always --compact --display-incomplete --display-skipped --display-notices --display-warnings

      - name: Archive logs ğŸ—„ï¸
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Laravel Log
          path: ./storage/logs/laravel.log
